# Generated by Django 5.0.7 on 2024-08-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JourneyQuest_App', '0002_alter_book_personaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Personaldata',
            field=models.CharField(max_length=500),
        ),
    ]
