# Generated by Django 5.0.7 on 2024-08-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JourneyQuest_App', '0003_alter_book_personaldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Personaldata',
        ),
    ]
