# Generated by Django 5.0.7 on 2024-08-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JourneyQuest_App', '0004_remove_book_personaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Pdata',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
