# Generated by Django 5.0.7 on 2024-08-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JourneyQuest_App', '0005_book_pdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Pdata',
            field=models.TextField(),
        ),
    ]
