# Generated by Django 5.0.7 on 2024-08-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JourneyQuest_App', '0006_alter_book_pdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Pdata',
            new_name='Personaldata',
        ),
    ]
